# Generated by Django 5.2.14 on 2026-05-27 04:42

import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=10)),
                ('message', models.TextField()),
                ('affected_field', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP fuel'), ('SAP_PROCUREMENT', 'SAP procurement'), ('UTILITY_ELECTRICITY', 'Utility electricity'), ('TRAVEL_FLIGHT', 'Travel flight'), ('TRAVEL_HOTEL', 'Travel hotel'), ('TRAVEL_GROUND', 'Travel ground')], max_length=32)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_date', models.DateField(help_text='Date the emission activity occurred (not ingestion date).')),
                ('period_start', models.DateField(blank=True, help_text='Billing / reporting period start (utilities).', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Billing / reporting period end (utilities).', null=True)),
                ('raw_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=32)),
                ('normalized_value_kg', models.DecimalField(decimal_places=6, help_text='Always kgCO2e after unit + factor normalization.', max_digits=20)),
                ('emission_factor_used', models.DecimalField(decimal_places=8, max_digits=20)),
                ('emission_factor_source', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, help_text='Plant code, meter address, or airport pair.', max_length=512)),
                ('vendor_or_carrier', models.CharField(blank=True, max_length=255)),
                ('source_row_hash', models.CharField(db_index=True, help_text='SHA-256 of raw source row for idempotent deduplication.', max_length=64)),
                ('is_edited', models.BooleanField(default=False, help_text='True if an analyst modified values post-ingestion.')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmissionRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP fuel'), ('SAP_PROCUREMENT', 'SAP procurement'), ('UTILITY_ELECTRICITY', 'Utility electricity'), ('TRAVEL_FLIGHT', 'Travel flight'), ('TRAVEL_HOTEL', 'Travel hotel'), ('TRAVEL_GROUND', 'Travel ground')], max_length=32)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_date', models.DateField(help_text='Date the emission activity occurred (not ingestion date).')),
                ('period_start', models.DateField(blank=True, help_text='Billing / reporting period start (utilities).', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Billing / reporting period end (utilities).', null=True)),
                ('raw_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=32)),
                ('normalized_value_kg', models.DecimalField(decimal_places=6, help_text='Always kgCO2e after unit + factor normalization.', max_digits=20)),
                ('emission_factor_used', models.DecimalField(decimal_places=8, max_digits=20)),
                ('emission_factor_source', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, help_text='Plant code, meter address, or airport pair.', max_length=512)),
                ('vendor_or_carrier', models.CharField(blank=True, max_length=255)),
                ('source_row_hash', models.CharField(db_index=True, help_text='SHA-256 of raw source row for idempotent deduplication.', max_length=64)),
                ('is_edited', models.BooleanField(default=False, help_text='True if an analyst modified values post-ingestion.')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical emission record',
                'verbose_name_plural': 'historical emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
