# Generated by Django 5.2.14 on 2026-05-27 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyflag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='ingestion_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.ingestionjob'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='emission_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='emissions.emissionrecord'),
        ),
        migrations.AddField(
            model_name='historicalemissionrecord',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemissionrecord',
            name='ingestion_job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.ingestionjob'),
        ),
        migrations.AddField(
            model_name='historicalemissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemissionrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='emissions_e_tenant__1dfd87_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='emissions_e_tenant__2d142c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_e_tenant__80b9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='emissions_e_tenant__a4863c_idx'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_row_hash'), name='unique_emission_per_tenant_hash'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['tenant', 'flag_type'], name='emissions_a_tenant__1b4e24_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['tenant', 'severity'], name='emissions_a_tenant__6a8c69_idx'),
        ),
    ]
