# Generated by Django 5.2.14 on 2026-05-27 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EDIT', 'Edit'), ('LOCK', 'Lock')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='emissions.emissionrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='reviews_rev_tenant__3d592b_idx'), models.Index(fields=['tenant', 'action'], name='reviews_rev_tenant__d68695_idx')],
            },
        ),
    ]
